# Generated by Django 5.1 on 2024-09-05 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_shipping_city_remove_shipping_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='city',
            field=models.CharField(default='Dallas', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipping',
            name='country',
            field=models.CharField(default='USA', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipping',
            name='post_code',
            field=models.CharField(default=77025, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipping',
            name='state_district',
            field=models.CharField(default='Texas', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipping',
            name='street_address',
            field=models.CharField(default='123 Sesame St.', max_length=100),
            preserve_default=False,
        ),
    ]
