# Generated by Django 5.1 on 2024-09-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_shipping_city_shipping_country_shipping_post_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='customer_service_email',
            field=models.CharField(default='customeremail@email.com', max_length=100),
            preserve_default=False,
        ),
    ]
